# Site settings
title: My note book
email: ljinke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Markdown is a awesome tool to write notes especially for programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ljinke.github.io" # the base hostname & protocol for your site
github_username:  ljinke

# Build settings
markdown: kramdown
